spring.application.name=charity-draw-backend
spring.datasource.url=jdbc:mysql://localhost:3306/charity_draw
spring.datasource.username=root
spring.datasource.password=1312004KOLI

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true